import Head from 'next/head';

const Home = () => {
  return (
    <div>
      <Head>
        <title>The Trav Channel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>the trav channel</main>
    </div>
  );
};

export default Home;
